### ISSUE TITLE
Image Grid should check whether a data subset match

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-imageanalytics#166]
##### Expected behavior

Image Grid should correctly check whether data in the subset match to those in a dataset.
I suggest checking whether the image name is the same in the subset.

##### Actual behavior
The wrong condition was removed in #164.

**Comment by ajdapretnar** [comment]
Fixed via #165.

**Comment by PrimozGodec** [comment]
This one is not fixed yet. The better condition still need to be made. :)
