### ISSUE TITLE
image embedding widget is lacking

### ISSUE THREAD

**Issue by guimby** [biolab/orange3-imageanalytics#87]
##### Image Analytics version
0.1.15

##### Orange version
3.8.0

##### Expected behavior
image embedding widget can be see and used

##### Actual behavior
image embedding widget can't be find from the left menu nor with a search from a new link 

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/35764225/35328397-9f63c19a-0115-11e8-8f42-60e57569b5d0.png)

**Comment by ajdapretnar** [comment]
@guimby Thanks for reporting this. Could you please also specify how you installed Orange and add-on?
Is it a Miniconda version of Orange? Or standard one? Did you install the add-on via Options - Add-ons?

**Comment by PrimozGodec** [comment]
@guimby If you installed add-on via Options - Add-ons, can you check if `Install add-ons with conda` is checked in Options - Settings - Add-ons.

**Comment by f-rumblefish** [comment]
Dear all:

I have the same problem of missing the "image embedding" widget under Orange3 3.8.0 and Orange3-ImageAnalytics 0.1.15 on Windows 10.

Several months ago, I had installed Anaconda on my desktop. Orange was inside the Anaconda and Image Analytsics 0.1.12 (with "image embedding") was fine. This week I notice that the "image embedding" widget is gone (while I am not sure if my Anaconda config has any changes). Updating Image Analytics from Options/Add-ons (with and without checking add-ons with conda) will result in failure of "pip -m install --upgrade --no-deps Orange3-ImageAnalytics existed with non zero status."

So, I manualy download Image Analytics from this site, run "python set.up install", and launch "python -m Orange.canvas". Now, Image Analytics is 0.1.15 but missing "Image Embedding".

**Comment by PrimozGodec** [comment]
I still cannot reproduce this bug. As you described all your errors happen when using `pip`. Can you check `Install add-ons with conda` property and try to install again since new Conda builds are available?

**Comment by PrimozGodec** [comment]
Closing due to inactivity. You are welcome to reopen it if the bug still present.

**Comment by umendi** [comment]
Can this issue be reopened? I am experiencing the same here:

MacOS 10.9.5
I updated Orange from 3.5 to current 3.13 (due to the add-ons issue solved on Apr.23rd) by downloading the DMG package and replacing the old version.

Due to a previously solved python compatibility issue I had because of my MacOS version, I executed the following command:
/Applications/Orange3.app/Contents/MacOS/pip install PyQt5==5.8.2

Opened Orange succesfully
Loaded all Add-ons succesfully
Installed Image Analytics 0.2.0 successfully
(options, add-ons Install add-ons with conda checked)

Only Import Images, Image Viewer and Image Grid widgets appear under the Image Analytics section

I have no other add-on installed.

**Comment by PrimozGodec** [comment]
@umendi Thank you for reporting the issue. 

Can you please execute following command:

    /Applications/Orange3.app/Contents/MacOS/pip freeze

and copy the output here to see if there is an issue with dependencies.

**Comment by umendi** [comment]
Thanks for the reply. This is the result:

Last login: Fri May  4 00:08:34 on console
apples-MacBook-Pro:~ apple$ /Applications/Orange3.app/Contents/MacOS/pip freeze
AnyQt==0.0.8
attrs==17.4.0
beautifulsoup4==4.6.0
biopython==1.71
boto==2.48.0
boto3==1.7.11
botocore==1.10.11
Bottleneck==1.2.0
brotlipy==0.7.0
bz2file==0.98
CacheControl==0.12.4
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
CommonMark==0.7.3
docutils==0.13.1
docx2txt==0.7
future==0.16.0
gensim==3.4.0
h2==2.6.2
hpack==3.0.0
hyperframe==3.2.0
hypertemp==0.8.0
idna==2.6
jmespath==0.9.3
joblib==0.11
keyring==10.3.1
keyrings.alt==2.2
lockfile==0.12.2
lxml==4.2.1
more-itertools==4.1.0
msgpack-python==0.5.6
nltk==3.2.5
numpy==1.12.1
oauthlib==2.0.7
odfpy==1.3.6
Orange3==3.13.0
Orange3-Educational==0.1.7
Orange3-ImageAnalytics==0.2.0
Orange3-Text==0.3.0
pdfminer3k==1.3.1
Pillow==5.1.0
pluggy==0.6.0
ply==3.11
py==1.5.3
pycparser==2.18
PyQt5==5.8.2
pyqtgraph==0.10.0
PySocks==1.6.8
pytest==3.5.1
python-dateutil==2.7.2
requests==2.18.4
requests-oauthlib==0.8.0
rfc3986==1.1.0
s3transfer==0.1.13
scikit-learn==0.18.2
scipy==0.19.1
serverfiles==0.2.1
setuptools-git==1.2
simhash==1.9.0
sip==4.19.3
six==1.11.0
smart-open==1.5.7
tweepy==3.6.0
typing==3.6.4
urllib3==1.22
validate-email==1.3
wikipedia==1.4.0
xlrd==1.0.0
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by joaoalves12** [comment]
Iam facing the same problem too by downloading the DMG package.
MacOS 10.11.6 
Orange 3.13
Image Analytics 0.2.0

**Comment by PrimozGodec** [comment]
@umendi and @joaoalves12: Since I still can not reproduce the error I ask you if you can please run

    /Applications/Orange3.app/Contents/MacOS/Orange -l 4

from the terminal and report the output you get in the command line when Orange is set up here. It should show us the reason for missing widget.

**Comment by umendi** [comment]
Thanks for your reply and follow up @PrimozGodec 

I executed the command and it opened Orange. The output in the terminal I got is as follows:

```
Last login: Fri May 11 11:11:02 on ttys000
apples-MacBook-Pro:~ apple$ /Applications/Orange3.app/Contents/MacOS/Orange -l 4
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Scheme node properties sync (changed: False)
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<Orange.canvas.scheme.widgetsscheme.WidgetsScheme object at 0x111a989d8>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Loading widget registry cache ('/Users/apple/Library/Caches/Orange/3.13.0/canvas/registry-cache.pck').
Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/data/contexthandlers.py'.
Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/visualize/owscatterplotgraph.py'.
Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/visualize/owtreeviewer2d.py'.
Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/visualize/pythagorastreeviewer.py'.
Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/evaluate/contexthandlers.py'.
Ignoring '/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/evaluate/utils.py'.
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/apple/Library/Application
[nltk_data]     Support/Orange/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/apple/Library/Application
[nltk_data]     Support/Orange/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/apple/Library/Application
[nltk_data]     Support/Orange/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package opinion_lexicon to
[nltk_data]     /Users/apple/Library/Application
[nltk_data]     Support/Orange/nltk_data...
[nltk_data]   Package opinion_lexicon is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/apple/Library/Application
[nltk_data]     Support/Orange/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/apple/Library/Application
[nltk_data]     Support/Orange/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_treebank_pos_tagger to
[nltk_data]     /Users/apple/Library/Application
[nltk_data]     Support/Orange/nltk_data...
Error while importing 'orangecontrib.imageanalytics.widgets.owimageembedding'. The widget will not be shown.
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 491, in asmodule
    return __import__(module, fromlist=[""])
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/imageanalytics/widgets/owimageembedding.py", line 21, in <module>
    from orangecontrib.imageanalytics.image_embedder import ImageEmbedder
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/orangecontrib/imageanalytics/image_embedder.py", line 19, in <module>
    from PIL import ImageFile
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/ImageFile.py", line 30, in <module>
    from . import Image
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: dlopen(/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib
[nltk_data]   Package maxent_treebank_pos_tagger is already up-to-
[nltk_data]       date!
Saving widget registry cache with 107 entries ('/Users/apple/Library/Caches/Orange/3.13.0/canvas/registry-cache.pck').
'set_global_registry()' - setting registry.
Setting registry '<Orange.canvas.registry.qt.QtWidgetRegistry object at 0x111abeb88> on 'CanvasScene(objectName='', ...)'.
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Orange3-ImageAnalytics 0.2.0
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Orange3 3.13.0
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Orange3-Educational 0.1.7
Invalid replacement fields {'DEVELOP_ROOT'}
Created <class 'Orange.canvas.help.provider.HtmlIndexProvider'> provider for Orange3-Text 0.3.0
```

**Comment by PrimozGodec** [comment]
@umendi it seems that there is an issue with the newest version of Pillow package. Can you just downgrade the version and let me know if it works for you:

    /Applications/Orange3.app/Contents/MacOS/pip install Pillow==5.0.0

**Comment by PrimozGodec** [comment]
@umendi thank you for your help. 
The issue is now fixed in this pull request https://github.com/biolab/orange3-imageanalytics/pull/106

**Comment by joaoalves12** [comment]
Well done @PrimozGodec! Thank you

**Comment by raybg** [comment]
I am still getting this issue in 3.23.1 Orange Version and Image Analytics - 0.5.3. 
Since the issue was reported 2 yrs back, i hope it should run just fine along with a simple add-on. Using it via Anaconda Navigator

**Comment by ajdapretnar** [comment]
Orange is now in version 3.27. Also, did you follow the instructions for installing on Anaconda? https://orange.biolab.si/download/#windows
